[project]
name = "dcmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docker>=7.1.0",
    "dotenv>=0.9.9",
    "fastmcp",
    "openai>=1.101.0",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
